### ISSUE TITLE
Unable to encode emoji in `Page URL`

### ISSUE THREAD

**Issue by redwerkz** [LinkStackOrg/LinkStack#425]
BaconQrCode\Exception\WriterException
Could not encode content to ISO-8859-1

resources/views/layouts/sidebar.blade.php:725

>      <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
>
>      <div class="modal-dialog">
>
>          <div class="modal-content">
>
>              <div class="modal-header">
>
>                  <h5 class="modal-title" id="staticBackdropLabel">Scan QR Code</h5>
>
>                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
>
>              </div>
>              @php
>                $qrCodeData = url('@'.Auth::user()->littlelink_name);
>
>                $renderer = new ImageRenderer(
>
>                    new RendererStyle(400),
>                    new SvgImageBackEnd()
>
>                );
>                $writer = new Writer($renderer);
>
>                $svgImageData = $writer->writeString($qrCodeData);
>
>                $svgImageBase64 = base64_encode($svgImageData);
>
>                $imgSrc = 'data:image/svg+xml;base64,' . $svgImageBase64;
>            @endphp

Context

>{
>    "id": 1140,
>    "littlelink_name": "♾️",
>}

**Comment by JulianPrieber** [comment]
Now suppressing errors; fixed in `beta 7`
