### ISSUE TITLE
Login "Remember Me" cookie not saved

### ISSUE THREAD

**Issue by toddlyons** [LinkStackOrg/LinkStack#429]
My credentials are not saved no matter how many times I click this box when logging in. 

In combination with the 419 error, it's pretty tiresome to have to reenter this repeatedly.

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/issues/428

**Comment by JulianPrieber** [comment]
Fixed: https://github.com/LinkStackOrg/LinkStack/commit/f0c96b954a29fe5455f6804dc3a24056808651b4
