### ISSUE TITLE
Vcard adds 'HOME' and 'WORK'

### ISSUE THREAD

**Issue by prosperot** [LinkStackOrg/LinkStack#434]
Platform: `Ubuntu 22.04 LTS`
Server type: `NGINX/Apache2 ...`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

in the VCARD file, the words HOME and WORK are added to the end of the ADR lines. 
eg:
ADR;WORK;POSTAL;CHARSET=utf-8:;;;;;;HOME
ADR;WORK;POSTAL;CHARSET=utf-8:1600 Pennsylvania Avenue;;Washington DC;;20500;USA;WORK

**Comment by JulianPrieber** [comment]
Nothing I can do about there.

Please direct all bugs reports here: https://github.com/jeroendesloovere/vcard
