### ISSUE TITLE
Changing the prefix to empty in advanced config breaks the dashboard

### ISSUE THREAD

**Issue by enthuzy** [LinkStackOrg/LinkStack#451]
Platform: `AlmaLinux v8.8.0 STANDARD virtuozzo`
Server type: `Apache/2.4.57`
PHP version: `8.1`
LinkStack version: `4.0.2'

Changing the below setting to empty breaks the dashboard and preview on the default page (results in 404 error). 

```
// The URL prefix is the symbol that comes before a LinkStack URL.
    // For example the '@' in 'example.com/@admin'.
    // If empty no prefix is required.
    'custom_url_prefix' => '+',
```

**Comment by JulianPrieber** [comment]
Fixed in `v4.0.4-beta-2`
