### ISSUE TITLE
How to Edit Buttons

### ISSUE THREAD

**Issue by Cousclou** [LinkStackOrg/LinkStack#461]
Hi,

I would like to know if it is possible to edit the buttons?

I would like to be able to add Steam instead of "Mastodon".

https://zpl.cous.re/u/VVeskC.png

**Comment by JulianPrieber** [comment]
This commit show you how to add a custom icon. The icons use font awesome.
This will reset if you update your app.

https://github.com/LinkStackOrg/LinkStack/commit/972e7c7c96dd7ba6c9cde87ffe378c68a7fe337b

**Comment by brasofilo** [comment]
For anyone needing the StackOverflow icon, use the following to make the icon with a dash in the name work:

```php
#app/Http/Controllers/UserController.php
saveIcon('stack-overflow', $request->{'stack-overflow'});

#resources/views/studio/links.blade.php
{!!icon('stack-overflow', 'StackOverflow')!!}
```

**Comment by JulianPrieber** [comment]
Here is a full list. It uses the same writing style of font awesome:
https://fontawesome.com/search?o=r&m=free&f=brands

**Comment by brasofilo** [comment]
Great to have the full list, thanks!

My issue was here: `$request->stack-overflow` is not valid, it has to be `$request->{'stack-overflow'}`

**Comment by JulianPrieber** [comment]
Huh, I didn't even notice that. 
Right, that's the only way I see to do this here. Didn't even think of that when implementing this.
This might become useful for future additions, thanks for pointing this out!
