### ISSUE TITLE
Broken capitalization in predefined button templates

### ISSUE THREAD

**Issue by elsiehupp** [LinkStackOrg/LinkStack#466]
By default, "GitHub" appears as "Github":

<img alt="predefined-site-dropdown" src="https://github.com/LinkStackOrg/LinkStack/assets/9206310/6bfa9e71-a555-4491-8c39-ffb48fb82483">

And this carries over to the actual button itself:

<img width=316 alt="default-button" src="https://github.com/LinkStackOrg/LinkStack/assets/9206310/fd19047c-8938-4d1a-920c-155d77b1f430">

I searched for the word "github" in the source code, and it looks like this shouldn't be happening?

https://github.com/LinkStackOrg/LinkStack/blob/4ba8b47aa7ad0f8dbc7d39a9157f8808e2df6c7b/config/button-names.php#L14

Anyway, what I did was I just used "GitHub" (i.e. the correct capitalization) as a custom button name, but this shouldn't be necessary, no?

Actually, judging by the names of the other list entries, it seems like they might use automatic capitalization of some sort. For instance, "Humble Bundle" appears as "Humble-bundle", and "OpenStreetMap" appears as "Openstreetmap". On the other hand, "Buy Me a Coffee" appears as "Buy Me A Coffee" (with a capitalized "A"), suggesting a particular pattern...

I don't know PHP specifically, so I can't easily speak to where this is happening, but I assume there's some function call that is reformatting the template name strings according to automated patterns, rather than using the correct capitalization as specified in `button-names.php`.

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/commit/87dbdebb1f06f81a4479c74eafc8e147632b0238
