### ISSUE TITLE
Custom Link Block Causes Crash

### ISSUE THREAD

**Issue by itswzyss** [LinkStackOrg/LinkStack#481]
Platform: `Ubuntu 22.04 LTS`
Server type: `Docker`
PHP version: `8.2.7`

When setting up a custom link, upon saving it seems to crash:

`DOMDocument::loadHTML(): Argument #1 ($source) must not be empty`

See https://flareapp.io/share/87negL6P

**Comment by itswzyss** [comment]
Please ignore -- I found the actual cause of issue, opening over on the Docker project.

**Comment by JulianPrieber** [comment]
Kown issue. Fixed in the latest beta.
