### ISSUE TITLE
Cannot install linkstack in website root

### ISSUE THREAD

**Issue by JMcrafter26** [LinkStackOrg/LinkStack#494]
Like the title suggests, I cannot install linkstack in my website root.

Linkstack however works when installing in website.com/linkstack/, but not in website.com/. Isn't this strange?
I created a subdomain dedicated to linkstack, but now it doesn't work in the website root. By “not working” I mean, that I get an 500 Error when visiting linkstack: 
![screely-1689693053767](https://github.com/LinkStackOrg/LinkStack/assets/77780772/a2ebe32c-647f-4b09-a82f-090067ec8b44)

Does anyone know how to fix this?

Platform: `Linux, Litespeed Web`
Server type: `Apache2`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

**Comment by JulianPrieber** [comment]
Please enable debugging in your config, or post the error in your Laravel log here

**Comment by JMcrafter26** [comment]
How can I enable this if I didn't even installed it?

**Comment by JulianPrieber** [comment]
You can just set it manually by editing your .env file in the root directory:

```
#Debug Settings=Changes if your page should display a full error description instead of a generic error 500.
#=App_debug either true or false. You might want to change this to false after you're done installing, but it's very useful for troubleshooting.
APP_DEBUG=true
#=App_env either local or production. Change this to production if you set the value above to false.
APP_ENV=local
LOG_CHANNEL=stack
LOG_LEVEL=debug
```

This is turned on by default, so I'm not sure why it's even off in the first place.

**Comment by JMcrafter26** [comment]
I cannot find a file named ".env" (And yes I have dotfiles visible).
Also for context, I moved the contents of socials.jm26.net/linkstack/ to socials.jm26.net/ (This is my domain for linkstack, and there you can see the 500 Error)

**Comment by JulianPrieber** [comment]
> I cannot find a file named ".env" (And yes I have dotfiles visible).

Then that might be your issue right there

**Comment by JMcrafter26** [comment]
I created the ".env" file manually and pasted the debug code.
Now the website I can see some debug stuff:
`No application encryption key has been specified.`

But you can take a look yourself: [socials.jm26.net](https://socials.jm26.net)

**Comment by JulianPrieber** [comment]
Please make sure the .env file has the right file permissions. The app normally generates its own key.

Otherwise follow the instructions on the error page.

**Comment by JMcrafter26** [comment]
I got it working, thank you!
The error was the missing .env file, somehow it didn't get transferred properly.

**Comment by mitexleo** [comment]
Faced the same issue. Why the release file doesn't include .env?
