### ISSUE TITLE
Custom background cannot be removed

### ISSUE THREAD

**Issue by Sad-theFaceless** [LinkStackOrg/LinkStack#495]
Hello!

When I upload a custom background, I can't remove it by clicking on the "Remove background" button. It reloads the current page (`/studio/theme`), the button "Remove background" is still here, and the background stays.

I tried this on both [linksta.cc](https://linksta.cc/) and [yrtree.me](https://yrtree.me/) instances

**Comment by JulianPrieber** [comment]
What happens if you do it twice in a row?

**Comment by JulianPrieber** [comment]
Ahhh, I know why

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/issues/480

**Comment by JulianPrieber** [comment]
@lastsamurai26

**Comment by JulianPrieber** [comment]
@Sad-theFaceless This is fixed in the latest beta.
We'll issue a patch later this day.

_Fixed in latest beta_
