### ISSUE TITLE
Button Icons are not being displayed

### ISSUE THREAD

**Issue by JMcrafter26** [LinkStackOrg/LinkStack#496]
Hello there,

like the title suggests, the button icons are not visible (see image).
I don't know if this was caused by the update or by an invalid setting, but fact is, it doesn't work.

When visiting a profile page, in the console we can see that the requested icon was not found:
`GET http://www.assets/linkstack/icons/github.svg`
This is being caused by the domain not being set correctly (The instance was installed in the root and the assets/linkstack/icons/ folder with the icons is available)

How can I fix this issue? Was this caused by me or the update?

Image:
![screely-1689784208403](https://github.com/LinkStackOrg/LinkStack/assets/77780772/6698307c-13d9-4abb-acc1-b4d57908b34b)
![image](https://github.com/LinkStackOrg/LinkStack/assets/77780772/11b9721f-45f6-420d-9488-ed778b5f3324)

Platform: `Linux`
Server type: `Apache2 ...`
PHP version: `8.1`

[//]: # (Please make sure you have read the system requirements at https://llc.ovh/req before submitting your issue.)

**Comment by JulianPrieber** [comment]
Could you share a link to your page?

**Comment by JMcrafter26** [comment]
Yes here it is: [https://socials.jm26.net/@admin](https://socials.jm26.net/@admin)

**Comment by JulianPrieber** [comment]
I'm not sure what's happening there. We don't use relative paths for URLs, so this does not make any sense to me.

I wasn't able to reproduce this on any instance, so I'd say the issue has to be something on your end.

**Comment by JMcrafter26** [comment]
Do you have any idea how to fix this? Are these settings stored in the database or in a config file?

**Comment by JulianPrieber** [comment]
Nope, I got nothing. You might want to try setting up a brand-new instance under the same vhost setup to check if that's cuasing it.

**Comment by JMcrafter26** [comment]
> Nope, I got nothing. You might want to try setting up a brand-new instance under the same vhost setup to check if that's causing it.

Do you think I should also delete the config file? (This would be the 5th time setting up linkstack 😂😭😭)

**Comment by JulianPrieber** [comment]
You'll have to track back to when this started, either reverse to a point where whatever causes this is undone, or start troubleshooting and rule out potential causes this way.

**Comment by JMcrafter26** [comment]
I was about to delete the instance and replace it whit the backup, when all of the sudden it started working again. Could you please verify that it works? (Please delete the cache, before doing so) Because if it works not just for me, then maybe it was a temporary issue or a problem with CLOUDFLARE or something like that.

**Comment by JMcrafter26** [comment]
Ok thank you for your reply. 
I think the cause was cloudflares caching system.
Thank you for your support, I will close this issue now
