### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'auth_as' in 'where clause' 

### ISSUE THREAD

**Issue by windslash31** [LinkStackOrg/LinkStack#501]
i tried updating my Linkstack Version to 4.2.0 and got this error, tried to update again to 4.2.1 and it still throws me this error, any idea what happened? it was working fine on previous release before 4.2.0. i attached the logs below. any help would be appreciated, thanks a lot

[laravel.log](https://github.com/LinkStackOrg/LinkStack/files/12141046/laravel.log)

**Comment by lastsamurai26** [comment]
do you using mysql oder sqlite ? 
if you are using mysql. 

it is already reported We are currently in the process of finding a fix

**Comment by JulianPrieber** [comment]
Please update to the latest beta version until version 4.2.2 is released

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/releases/tag/v4.2.2

**Comment by windslash31** [comment]
hello, i tried updating to 4.2.2, in this version i can get into the dashboard just fine, but when i open "manage users" it throws the same error as before. i attached the logs below. and yes im using mysql for my database. thanks


[laravel.log](https://github.com/LinkStackOrg/LinkStack/files/12156897/laravel.log)

**Comment by JulianPrieber** [comment]
@windslash31 You are running LinkStack with XAMPP on Windows?

And you are able to update?
