### ISSUE TITLE
Updating on shared hosting

### ISSUE THREAD

**Issue by elimae17** [LinkStackOrg/LinkStack#509]
Hi,

I tried updating LinkStack with the automatic updater but it doesn't get past the backup process and then I get a 500 Internal Server error. I am on shared hosting using LiteSpeed Web Server.

![Screenshot](https://github.com/LinkStackOrg/LinkStack/assets/106697497/54839bc3-ba4f-4e9f-8185-0678fbf3f080)

I tried turning Debugging on but that didn't change anything.

I would appreciate any help!

**Comment by JulianPrieber** [comment]
Maybe turn off update backups

**Comment by elimae17** [comment]
Thanks for the suggestion! It didn't work the first time but then it did!

**Comment by elimae17** [comment]
I have to reopen this issue again.

I could update past versions but as I initialy stated only when trying multiple times. So out of let's say 10 times I tried updating, it failed 9 times and suddenly worked. But I always got an error message, never a success message. So it always thorwed an 500 Internal sever error but at some point, when I went back to the dashboard, I already had the newest version.

However right now, when I try to update from 4.5.0 to 4.5.1 it doesn't work, no matter how often I try. I also get the 500 error page much quicker than before. When I turn on debugging I get this message:

![Screenshot 2023-12-12 at 15-51-31 The _tmp_4 5 1 directory does not exist](https://github.com/LinkStackOrg/LinkStack/assets/106697497/5e400174-53f3-4538-b477-2b33e7227241)

I am not a web developer and use this service only on shared hosting so unfortunately I cannot really make sense out of this error handling.

I would be grateful for any help.

**Comment by JulianPrieber** [comment]
We do not support updating on most shared hosting providers.

**Comment by elimae17** [comment]
i see. strange that it worked before. 

so i guess i have to update manually then. it says that in the readme file that some files need to be added to the SQlite file. but when i replace the sqlite file all settings will be resetted to default? how can i update without resetting?

**Comment by JulianPrieber** [comment]
It always depends on your provider. You need access to the tmp folder, which not all hosting providers allow you to access.
Some parts may still rely on shell access, which is also mostly restricted.

You may even have some problems with manual updates.
We still offer the manual update file so that you do not have to replace your database each time.

We may have to update the documentation for the manual update process.
You still have to run /update?finishing after each update.

**Comment by elimae17** [comment]
Thanks for the info!

I will ask my hosting provider about the tmp folder. I worked in the past so maybe they changed something...

I don't have access to the shell. I can only execute cron jobs. Could this be used as an alternative for necessary comands?

**Comment by JulianPrieber** [comment]
We are trying to move away from console commands for certain tasks. I think the basic updater should work fine without it as of now.

**Comment by elimae17** [comment]
So for the update to 4.6.0 it would be sufficient to just replace the files with the contents of the linkstack folder?

**Comment by elimae17** [comment]
I have received an update from my hosting provider. As expected, access to the tmp folder in the document root directory is not granted. They recommended to use a tmp folder in the user directory under `/home/myunsername/tmp`. (This is also the highest level I can access in our shared hosting, so the instance is also installed in `/home/myusernme/linkstack`). It would be really cool if automatic updates would also work on shared hosting in the future.

Nevertheless, I was able to update manually without replacing the SQlite file. The only problem I had was that my configuration (e.g. title of the site or which user serves as homepage) was reset to the default settings.

**Comment by JulianPrieber** [comment]
Heyho, I looked at the source code for the updater. Everything seems to be compatible.
Try adding

**Comment by elimae17** [comment]
Thanks, that sounds great! I will add it and try it out with the next release!

**Comment by JulianPrieber** [comment]
@elimae17 new update is out. Let me know how it goes. 👍

**Comment by elimae17** [comment]
Thanks for the reminder!

I added the `/home/myunsername/tmp` like my hosting provider suggested:
![Screenshot1](https://github.com/LinkStackOrg/LinkStack/assets/106697497/4df188b4-249d-49e8-8e22-21da4c6e6877)

And I no longer get any 500 server error messages. However, I now almost immediately get this error message:

https://github.com/LinkStackOrg/LinkStack/assets/106697497/12b26c74-cf10-4c0e-a29f-493123842ba3

**Comment by JulianPrieber** [comment]
Do you have SKIP_UPDATE_BACKUP enabled?

**Comment by elimae17** [comment]
Yes it is set to true. If set to false it loads very long and then I get a 500 server error, just as described in the first post of this thread.

**Comment by JulianPrieber** [comment]
Right, then this means this check fails: `$updater->source()->isNewVersionAvailable()`. It might be necessary to take it up with them: https://github.com/codedge/laravel-selfupdater.

**Some steps to fix this might be:**
- Making sure the version in version.json is lower than the one on GitHub
- Making sure the tmp file is empty
- Trying again

**Comment by JulianPrieber** [comment]
As far as we know, updating (except the backup) works on shared hosting, if the SELF_UPDATER_DOWNLOAD_PATH is defined correctly. We will address this in the future to use a folder in the app itself so the tmp folder is not required anymore

**Comment by JulianPrieber** [comment]
The update issue appears unrelated and seems to be an issue with https://github.com/codedge/laravel-selfupdater.
We don't know how what causes this issue.

**Comment by elimae17** [comment]
Well, thanks again for all your help regarding this issue! If I find something out I'll update this thread.

**Comment by JulianPrieber** [comment]
Looks like your download is capped at 8 Mbit. Normally, PHP can overwrite the curl timeout limit and the updater package may do that already. I'm not sure if your hoster allows that.

What you want to edit is:
`CURLOPT_CONNECTTIMEOUT` - The number of seconds to wait while trying to connect. Use 0 to wait indefinitely.
`CURLOPT_TIMEOUT` - The maximum number of seconds to allow cURL functions to execute.

**Comment by elimae17** [comment]
Thanks for the fast reply! Can I edit these myself or do I need to ask my hosting provider for that?

**Comment by JulianPrieber** [comment]
I couldn't find a way to increase the CURLOPT_TIMEOUT other than directly in the code.
I had to dig into the source code of our [updater dependency](https://github.com/codedge/laravel-selfupdater) and the download function does not give a timeout limit, resulting in the default of 30 seconds being used.
https://github.com/codedge/laravel-selfupdater

As far as I can tell, pretty much our only option here is to contact the developer or open a pull request. This could take a while until we can update. And then you'd have to update to be able to update...

**Comment by JulianPrieber** [comment]
Made a pull request: https://github.com/codedge/laravel-selfupdater/pull/504

**Comment by elimae17** [comment]
That's great. So now we have to wait for the developer to implement this change, right?

**Comment by JulianPrieber** [comment]
The change has been implemented.
It's live on `v4.8.0-beta-1`. The version isn't tested yet.

I had to update our framework for it to work. This version requires at least PHP 8.1.
You can update manually with https://beta.linkstack.org/ if you want to.

This might take a while until I can push the full release.

**Comment by elimae17** [comment]
That's very nice! I will install the beta on my test instance. But to then test the automatic updater, I'll have to wait for beta 2, right?

**Comment by JulianPrieber** [comment]
You can just change your version number or something. 
But if you're in beta mode, you can just update as often as you like, even when you're already on the latest version.
