### ISSUE TITLE
Can't change the icon size of custom links.

### ISSUE THREAD

**Issue by elimae17** [LinkStackOrg/LinkStack#511]
Hi,

I use one predefined website link and beyond that only custom links with custom Font Awesome icons. I would like to increase the size of the icons a bit but when I change the width and height parameters in the css file, only the website icon changes.

![screenshot1](https://github.com/LinkStackOrg/LinkStack/assets/106697497/6ece868d-3ce4-4b17-b8ce-81d9bb34eecd)
![screenshot2](https://github.com/LinkStackOrg/LinkStack/assets/106697497/2ac104fb-786b-42fd-a453-7a39d4e3f1f0)

I noticed that the website icon is an SVG from the assets folder, while the icons of the custom links are characters from the Font Awesome font family whose size depend on the font size of the button itself.

How can I change only the size of the icons of custom links? Or could I use custom SVGs for the custom links instead of them being an font right away?

**Comment by elimae17** [comment]
The only way I found so far would be to add a .fa class to the CSS file of the theme but I don't know if that is the recommended way...

**Comment by JulianPrieber** [comment]
You can change the size of Font awesome icons by using font-zize

**Comment by elimae17** [comment]
Thanks for the quick help!

I was just wondering if there is a way to use custom icons instead of the Font Awesome ones? I know I can add custom SVGs in the extra/custom-icons folder of my theme but these would just replace the standard icons from assets/linkstack/icons, right?

**Comment by JulianPrieber** [comment]
The custom icons are just to replace the already existing predefined brand icons

**Comment by elimae17** [comment]
So I can't add custom svg icons to custom link buttons, only the free Font Awesome icons?

**Comment by JulianPrieber** [comment]
You technically can change custom link icons.
If you have a Font Awesome premium subscription, you could use that.
