### ISSUE TITLE
Encoding issue when typing non-ASCII characters in bio

### ISSUE THREAD

**Issue by astrojuanlu** [LinkStackOrg/LinkStack#519]
When I type `él` in the bio, it gets transformed into `Ã©l` on save.

See: https://no.mbre.es/@astrojuanlu

**Comment by JulianPrieber** [comment]
Are you running no.mbre.es?

**Comment by astrojuanlu** [comment]
No

**Comment by JulianPrieber** [comment]
I can't see a way to contact them anywhere **on the site**, that's against the community instance [terms](https://linkstack.org/community-instance-terms/).

I guess this is a place where the owners of the site can be contacted? https://linkstack.org/community-instance-terms/
I'd suggest contacting the owners of the site about it.

If you can reproduce this on [linksta.cc](https://linksta.cc/) I'll look into it.

<br>

_Note to maintainers:_
When running MySQL, make sure to create the database with charset `utf8mb4` and collation `utf8mb4_unicode_ci`

**Comment by astrojuanlu** [comment]
Will let them know, thanks!
