### ISSUE TITLE
Adding analytics code is not working

### ISSUE THREAD

**Issue by fame-odoo** [LinkStackOrg/LinkStack#535]
Hi, thank you for the wonderful project!

I have been using Umami for a while and previously I was inserting my tracking code directly to the /resources/view, and it worked, but today after upgrade to 4.2.6 I found nothing works anymore even I put the <script> to the same location.

I also tried to insert it into advanced config and it is not showing in the head as well.

Could you please help on this? Thanks!

**Comment by JulianPrieber** [comment]
Does your tracking  code make a request over http?

**Comment by fame-odoo** [comment]
@JulianPrieber Hi thank you for the quick reply, I assume the answer should be no (but I am not sure) it is just a simple javascript code 

<script async src="https://hiddenforsecurity/mfydev" data-website-id="hiddenforsecurity"></script>

I can also post the javascript content here if you need

**Comment by JulianPrieber** [comment]
The script source is loading over HTTPS. The only real change in this update improved HTTPS redirection.
Every update will remove any code you added to your blade files. So if your content got removed there, that is expected.

The advanced config section should just work fine.
![chrome_G65zECyYsn](https://github.com/LinkStackOrg/LinkStack/assets/60265788/d246f4f7-08a2-486b-9972-c92cf90bc38c)

If you enter plain text in your analytic section in the advanced config, this will be printed on every page. I want able to reproduce a failure of this function on any version. Perhaps you entered your code in the wrong section?

**Comment by fame-odoo** [comment]
@JulianPrieber Oh I think what you say makes sense, could you please where should I insert the <script> to? it should be a file which is in the resources/views folder right?

If you don't mind could you please tell me where should I insert it?

Thanks a lot for any help or advice and I do appreciate a lot!

**Comment by JulianPrieber** [comment]
In your advanced config. You don't have to touch the code to do that. On your config page there is the advanced config section. There you'll find a clearly marked place to put your code. Let me know if you have any issues finding it.

**Comment by fame-odoo** [comment]
Here is where I added in the advanced config:
"""
<?php
$analytics =
/*
|--------------------------------------------------------------------------
| Analytics
|--------------------------------------------------------------------------
|
| Add external analytics services to your LinkStack instance by adding them below.
| Everything you enter below will be added to the <head> tag of every page.
| Formatting in plain HTML is expected.
|
*/
<<<EOD

<script async src="https://t.mfy.world/mfydev" data-website-id="2a602ae3-c925-4af7-a16e-26252bd81f14"></script>

EOD;;
return [
"""

And I went to the https://mfydev.link which is my self hosted linkstack, seems like the head does not have this, am I doing correctly?

**Comment by JulianPrieber** [comment]
This looks about right. How do you check if the code is actually added?

**Comment by JulianPrieber** [comment]
Does not seem that it's added to the page...

**Comment by fame-odoo** [comment]
By going to the inspect, I will check the head part in the Elements and there is nothing related to this, and my umami website cannot see any update tracking code as well

**Comment by fame-odoo** [comment]
Yes, seems like this part of the advanced config is not working?

**Comment by JulianPrieber** [comment]
I'd try to enter plain text there to see if that works.
Other than that, you might want to restore your advanced config to default and try again.

**Comment by JulianPrieber** [comment]
![chrome_69oFsYiPpX](https://github.com/LinkStackOrg/LinkStack/assets/60265788/d63892cf-93b8-40fe-baf3-9d85815a249f)
This works just fine for me

**Comment by fame-odoo** [comment]
I just tried to restore it to default and added a plain text Test and it is still not showing up, what I am gonna do is doing a quick fresh reinstall to test it. I will finish the reinstallation very fast and let you know.

Thanks a lot for your help!

**Comment by fame-odoo** [comment]
I just did a full reinstallation, and added the same thing to the right place. But seems like it is still not showing up

**Comment by fame-odoo** [comment]
![image](https://github.com/LinkStackOrg/LinkStack/assets/107050396/bef542ef-a036-4352-bb45-b128c042d986)
![image](https://github.com/LinkStackOrg/LinkStack/assets/107050396/4a12565f-041e-42be-ab73-222bd4654e06)

**Comment by fame-odoo** [comment]
@JulianPrieber and also this might not be related to the issue but I found when I try to set the language in app locale every time it will auto refresh the whole page. Seems like setting language is not working as well.

**Comment by JulianPrieber** [comment]
Looks like there is something going very wrong with your instance. The language setting is tested and working in all recent releases. 

You might have to troubleshoot on your own here or switch to the docker version to maximize compatibility.

**Comment by fame-odoo** [comment]
Sure no problem, I will change it to the docker version then.

Thank you so much for your time and replies. I am using php 8.2 don't know whether that is a problem or not but I am gonna test on docker

**Comment by fame-odoo** [comment]
Just changed to docker version and it is working now.

Thanks a lot for your time again!
