### ISSUE TITLE
Running LinkStack on localhost:8000 - Error: Undefined array key "QUERY_STRING"

### ISSUE THREAD

**Issue by tasmaniski** [LinkStackOrg/LinkStack#540]
I am trying to run LinkStack on my localhost with a PHP built-in web server. 

After downloading the last version, 
I run command:  `php -S localhost:8000` in root directory, where is the index.php file. 
But in browser I am getting the error: 
>  Undefined array key "QUERY_STRING"

I also did try with a php artisan serve  but also got different error: 
>   The provided cwd "/var/www/linkstack/public" does not exist. 

I am not sure if I should run in like this without Docker?

**Comment by JulianPrieber** [comment]
`php -S localhost:8000` is working for me.

For `php artisan serve` to work, you'll have to change `public_path()` to `base_path()` on line 145 in the file `vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php`.

These two options are only meant for development and should not be used inside a production environment.
To run this app, you simply put it onto any web server, preferably Apache, just like WordPress. See https://docs.linkstack.org/getting-started/requirements/.

**Comment by JulianPrieber** [comment]
PHP artisan serve works by default now in `v4.2.8-beta-1`

**Comment by tasmaniski** [comment]
Thanks for replay! 

It happens only after fresh download of the zip https://github.com/linkstackorg/linkstack/releases 
version 4.2.7

I added in index.php file at the beginning: 

```
if(!isset($_SERVER['QUERY_STRING'])){
    $_SERVER['QUERY_STRING'] = '';
}
```

That fix the issue on my machine. 
After installation I removed the code, and everything works.
