### ISSUE TITLE
Cannot exit unverified user impersonation 

### ISSUE THREAD

**Issue by alpsencer** [LinkStackOrg/LinkStack#563]
Platform: `Ubuntu 22.04 LTS`
Server type: `NGINX/Apache2 ...`
PHP version: `8.1`

I cannot exit user impersonation. Since the user is not verified, I cannot leave impersonation. I use the Docker version. I think the problem is fixed in the latest version, but is there any solution for the previous versions?

**Comment by JulianPrieber** [comment]
You have to edit your database manually to get out of this.
