### ISSUE TITLE
Labels longer than the button length don't render correctly.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [LinkStackOrg/LinkStack#594]
Specifically, they wrap properly, but the buttons don't increase in size dynamically in order to compensate for the label's width.

**https://linksta.cc/going/8345?https://linksta.cc/@RokeJulianLockhart#:~:text=20to%2520adopt-%2Cxenforo,Powered%20by%20LinkStack**

> ![image](https://github.com/LinkStackOrg/LinkStack/assets/42837531/663af55c-f7bc-4a12-868d-f54d33680489)

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/issues/405
