### ISSUE TITLE
419 when attempting to add link entry.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [LinkStackOrg/LinkStack#598]
0.	> ![image](https://github.com/LinkStackOrg/LinkStack/assets/42837531/0a7ee45e-3c3a-4130-95dd-60ee1a9d258a)
	
	> https://www.europeanmovement.co.uk/rokejulianlockhart

0.	> ![image](https://github.com/LinkStackOrg/LinkStack/assets/42837531/dfbe56cb-eb93-4a83-9819-ff683a11115b)

I am able to access the rest of the website (https://linksta.cc/dashboard and https://linksta.cc/studio/links) fine (of course except for https://github.com/LinkStackOrg/LinkStack/issues/599#issue-1948011176).

**Comment by RokeJulianLockhart** [comment]
Fixed. I had to wait a while, after which I was prompted to reauthenticate. It appears that periodic deauthentication isn't quickly synchronized across all of the system.

**Comment by JulianPrieber** [comment]
If your session expires, this is the expected behavior.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/598#issuecomment-1768409676

@JulianPrieber, it shouldn't be, because the reason for the expiry isn't communicated to the user, and they're not fully deauthenticated until a good 15 minutes after this begins.

This should be reopened until it is reproducible that no functionality is lost until the user is entirely deauthenticated, rather than a slow random loss of functionality.

**Comment by RokeJulianLockhart** [comment]
That'd be better, although the problem with that is that my authentication session hadn't expired, so I don't know whether that would merely redirect me to the dashboard (since I was technically authenticated in some places). See the top image for confirmation.

If that issue is fixed, yes, that would be great.

**Comment by JulianPrieber** [comment]
What you're experiencing then is most likely an XSRF-TOKEN mismatch, which is a security feature.

**Comment by JulianPrieber** [comment]
![chrome_zjGoFaMmkY](https://github.com/LinkStackOrg/LinkStack/assets/60265788/a5e1b473-376c-4b75-a220-3add13e1f324)

Some apps handle XSRF-TOKEN mismatches by invalidating the session and logging out the user.

The issue could be caused by opening a form on the app in one tab, then using the app in another, and then submitting the form in the previous tab.
