### ISSUE TITLE
Gracefully redirect when accessing valid URI without necessary context.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [LinkStackOrg/LinkStack#599]
*	**https://linksta.cc/studio/edit-link/**
	> ![image](https://github.com/LinkStackOrg/LinkStack/assets/42837531/e4673fde-c5f3-44ce-a4fb-304a7a3fd68a)
*	**https://linksta.cc/studio/**
	> ![image](https://github.com/LinkStackOrg/LinkStack/assets/42837531/7dcf4538-c2d3-499a-8555-44b279cb307d)

Accidentally backtracking to these is easy. The site should redirect to https://linksta.cc/dashboard from https://linksta.cc/studio/ and https://linksta.cc/studio/links from https://linksta.cc/studio/edit-link/.

**Comment by JulianPrieber** [comment]
Please check again now

**Comment by RokeJulianLockhart** [comment]
@JulianPrieber, same behaviour at aforementioned URIs.
