### ISSUE TITLE
rel="me" only in Mastodon links

### ISSUE THREAD

**Issue by mraitisoja** [LinkStackOrg/LinkStack#600]
Hello

I was adding my links to linkstack and noticed that only my mastodon link has link rel="me" so that it gets verified.
Other sites use the same mechanism to proof identity 

Is it possible to add rel="me" to others also or make it an option?

**Comment by MagicLike** [comment]
> Hello
> 
> I was adding my links to linkstack and noticed that only my mastodon link has link rel="me" so that it gets verified.
> Other sites use the same mechanism to proof identity 
> 
> Is it possible to add rel="me" to others also or make it an option?
> 

Should be a relatively easy fix!

**Comment by LeviSnoot** [comment]
If you provide examples of links that should have this functionality we can look into implementing it.

**Comment by mraitisoja** [comment]
> If you provide examples of links that should have this functionality we can look into implementing it.

Hello
Here's my main fediverse profile page (Streams) https://raitisoja.com/channel/make
and in the left side you can see that Links is not authenticated. 

Not sure if this is easy to do, because the URLs change per product.

**Comment by LeviSnoot** [comment]
> > If you provide examples of links that should have this functionality we can look into implementing it.
> 
> Hello Here's my main fediverse profile page (Streams) https://raitisoja.com/channel/make and in the left side you can see that Links is not authenticated.
> 
> Not sure if this is easy to do, because the URLs change per product.

I believe we can implement this. It looks like this is the project in question: https://codeberg.org/streams/streams

I'll just create a button for Streams, and include it in the `$relMe` array.

**Comment by mraitisoja** [comment]
Thank you
