### ISSUE TITLE
Linkstack won't update

### ISSUE THREAD

**Issue by FuckingToasters** [LinkStackOrg/LinkStack#606]
### LinkStack version

4.2.8

### Description

I constantly have following notification:
![image](https://github.com/LinkStackOrg/LinkStack/assets/94435104/b279e1ad-0cab-443e-90fb-ea2b3b1acb01)

After clicking on the notification i see following:
![image](https://github.com/LinkStackOrg/LinkStack/assets/94435104/70ba7fb8-415d-42dc-b654-ab5e30f3ac52)

Now after completing the update (which seem to be successful) i'm able to view release notes or visit the admin panel, sadly it seem to don't have updated anything at all.

I also tried skipping backup but issue is the same, also following error constnalty happen and i need to manually refresh the site in order to let it continue:
![image](https://github.com/LinkStackOrg/LinkStack/assets/94435104/88552376-777e-4290-84eb-d71ef0d1d753)

becasue i run linkstack inside a docker container, i also tried redeploying the image with :latest tag which hover did not seem to have updated it either.

### Details about your system

OS: Debian 12 x Docker
PHP Version 8.2.7

### How to reproduce

Probably by installing an older Linkstack release with docker and then trying to update it.

**Comment by FuckingToasters** [comment]
After manually updating to 4.3.0 whenever i try to add a link, a login page is placed inside.

I thought it had to do with expired session or whatever so i just logged in there but the login page don't want to go away.
![image](https://github.com/LinkStackOrg/LinkStack/assets/94435104/d37b46b2-7f8b-4bc7-b15a-d3ae0ea96398)

**Comment by JulianPrieber** [comment]
Does the same thing happen in Chrome and Firefox?

**Comment by FuckingToasters** [comment]
> Does the same thing happen in Chrome and Firefox?

I now tried it on chrome (mobile) and instead of the login page, i got unlimited loading (which i fixed by enabling the force all links to be https ption) but enableing this option breaks the mail verification system for me (due to an invalid signature error i mentioned in another issue)

**Comment by JulianPrieber** [comment]
This is most likely part of your original issue. We have seen this kind of issue before when the vhost doesn't work properly.
You should be able to confirm this by accessing your page directly over your published port.

Unless we are able to reproduce this issue there is nothing we can do here.
You might be able to get some help on our community discord, perhaps someone knows what to do in your specific case.
