### ISSUE TITLE
Attempt to read property "name" on null

### ISSUE THREAD

**Issue by FuckingToasters** [LinkStackOrg/LinkStack#607]
### LinkStack version

4.3.0

### Description

I have a user which supposently have 3 Links added if i trust the number shown in the Mange User Admin Page, when visiting the User's Profile no link shows up and when pressing the "impersonate user" button, clicking on the links section i get the error shown in the screenshot below:
![image](https://github.com/LinkStackOrg/LinkStack/assets/94435104/31a1ac95-37d1-4ec7-b43d-b96cba15ce96)

The affected user: https://stackzilla.vbucksgenerator.zip/@YAMAXD

### Details about your system

Debain 11
PHP 8.2.7
Laravel 9.52.16

### How to reproduce

Create an seerate useraccount, add few links to the account, imporsonate the account and try to visit the links section.

**Comment by pacholoamit** [comment]
I'm getting this as well

![image](https://github.com/LinkStackOrg/LinkStack/assets/69985528/22e130c1-bc43-480f-b116-0e06a9db7e9a)

**Comment by JulianPrieber** [comment]
This is a generic error. This is most times caused by some missing dependency in the system.
