### ISSUE TITLE
Escaping singlequote in advanced config causes Internal Server Error

### ISSUE THREAD

**Issue by FuckingToasters** [LinkStackOrg/LinkStack#612]
### LinkStack version

4.3.1

### Description

In the Advanced Config, i wanted to use an single quite in the array section for the example device page on the home page, adding an singlequote inside obviously need to be escaped by adding an backslash in front of it because otherwise the singlequote counts as end of the string and so the text afterwards wouldn't be in the string anymore.

So here is what i tried which caused the issue:
```php
      array(
        'button' => 'custom',
        'link' => 'https://stackzilla.vbucksgenerator.zip/@Infinimonster',
        'title' => 'Founder\'s Profile',
        'icon' => 'fa-hand-holding-heart',
        'custom_css' => 'color:#ffffff; background-image:radial-gradient(circle, #4b1977 0%, #2b0081 95%);'
      ),
    ),
```

As you can see, the issue this issue is about is inside the title section, after saving the config, linkstack turns into an blank page and the console shows `500: Internal Server Error`

In Order to solve this, i would need to delete the advanced-config.php in the linkstack folder after which the website works again and the advanced-config.php file is automatically recreated upon visiting the advanced config section.

Changes made to the config would need to be redone.

Regards,
FuckingToasters

### Details about your system

Debian 11
PHP 8.2.7
Version: 4.3.1

### How to reproduce

add an escapinged singlequite in the array section of the advanced config, refresh the site and see a completly blank pag with the statuscode `500: Internal Server Error` inside the networking tab or console of the devtools.

### Possible Solution

I'm not really sure how it could be solved.

**Comment by JulianPrieber** [comment]
You are editing a PHP file. You have to follow PHP syntax.
I might add some syntax validation if I find a way to do it.

We can't change anything about how this works. If you have a problem there, you can take it up with the big guys I guess: https://github.com/php/php-src
