### ISSUE TITLE
Automatic Updater - Beta

### ISSUE THREAD

**Issue by Mighty-Jay** [LinkStackOrg/LinkStack#615]
### LinkStack version

v4.3.1

### Description

So i have enabled the Beta in the config of LinkStack, and then have gone to update it using the automatic updater, but i keep getting a server 500 error. When enabling Debugging, there appears to be an issue with a specific bit in the code. IIS has access to Modify the files so it shouldn't permissions that are causing the issue. 

### Details about your system

OS: Windows Server 2019 Running IIS.
PHP: 8.2.7

### How to reproduce

Enable Beta in the config and try to update automatically, it fails every time. 

### Additional Context

Here is the logs for the issue: https://flareapp.io/share/47qKKAam#debug

**Comment by JulianPrieber** [comment]
Try enabling the PHP zip extension

**Comment by Mighty-Jay** [comment]
Amongst all the other PHP extensions that are enabled, PHP zip is already enabled. 
![image](https://github.com/LinkStackOrg/LinkStack/assets/48175432/d8b08083-045f-4f49-8bcb-ba7dee760be5)

**Comment by JulianPrieber** [comment]
Oh, I didn't see the Windows server there.
We don't test that updater.
I'll have to look into it.
