### ISSUE TITLE
Error to Access to Users after Updating

### ISSUE THREAD

**Issue by DerKartdomi** [LinkStackOrg/LinkStack#618]
### LinkStack version

4.4.0

### Description

After a Update i can't open the users Page
I get the Error `Undefined variable $badge`
![Screenshot_2023-11-10-17-19-33-825-edit_com android chrome](https://github.com/LinkStackOrg/LinkStack/assets/67392090/905819d5-44dc-4f50-b345-5401ff4bd14f)

### Details about your system

Plesk Webserver from a hoster

### How to reproduce

I only updated via Auto updater

**Comment by DerKartdomi** [comment]
Update: all links are in my database (mysql) but doesn't show up on website

**Comment by JulianPrieber** [comment]
Check your database. Entries in the Users block field cannot be NULL
