### ISSUE TITLE
Update minimum PHP requirements

### ISSUE THREAD

**Issue by avoidthehack** [LinkStackOrg/LinkStack#647]
Hi!

PHP 8.0 is completely deprecated as of Nov 2023. It is no longer receiving any security updates: https://endoflife.date/php

Recommend updating dependency/system checks for at bare minimum PHP 8.1 - it still has security updates for at least another year before it is completely deprecated as well. Ideally, it should be 8.2 as it has active support for at least another year, security support for 2 years.

**Comment by JulianPrieber** [comment]
LinkStack is fully compatible up to PHP 8.3 and our dependencies reflect that. We follow our own timeline, we may require at least PHP 8.1 in Q1 2024 and 8.2 from 2025 onwards.

I'd prefer if we would still support PHP 7.4, but we do make sure we are getting active security updates.

The docker version is running PHP 8.2. All our hosted servers are running at least PHP 8.2.
