### ISSUE TITLE
LeetCode Favicon not loaded

### ISSUE THREAD

**Issue by RuthlessRuler** [LinkStackOrg/LinkStack#651]
### LinkStack version

4.6.0

### Description

Favicon for LeetCode refuses to load. Doesn't show even after refreshing icon cache

### Details about your system

Windows 10, Firefox Browser

### How to reproduce

- Navigate to Add a link
- Use the Custom Link Block
- Use LeetCode.com for the Target URL
- Tick the option "Show website icon on button"

**Comment by JulianPrieber** [comment]
This should have been fixed with the new system.
