### ISSUE TITLE
Link with a port number fails to route correctly

### ISSUE THREAD

**Issue by aaronkampmeier** [LinkStackOrg/LinkStack#654]
### LinkStack version

Docker image: 4fdde50ad17c

### Description

I am attempting to use LinkStack to manage a number of links to internal pages for my homelab. Most of these pages do not run off of the standard HTTP ports (such as Homebridge using port 8581). I put in the full domain name with the port number into LinkStack expecting that, when clicked, I will be redirected to the same domain with the port number attached. However, when clicked, an error pops up saying that the web address is invalid. I believe this is because the colon denoting the port is not properly url encoded when navigating to the `http://linkstackserver.com/going/1?redirecting-to.com:8581`. 

In an attempt to work around this, I tried url encoding the port number when entering the link by entering something like `redirecting-to.com%3A8581`. However this still failed to route properly, this time failing with a php error of `Attempt to read property "link" on null`. Here is the error info: https://flareapp.io/share/B5ZZbvN5#context-user-user

### Details about your system

Raspbian OS arm64, docker linkstack

### How to reproduce

Add a link with a port number such as `example.com:8581`. Open the LinkStack page and try to click on that link.

### Possible Solution

Properly encode the `:` character when redirecting a link that contains it.

**Comment by JulianPrieber** [comment]
Can't reproduce. Make sure to save links in the correct formatting using http or https i.e. `http://redirecting-to.com:8581`.
Should be working for you regardless in `v4.7.0-beta-5`.

**Comment by aaronkampmeier** [comment]
Ah putting the scheme made it work now. Thanks for the heads up. I believe there still is a bug though: that the Add Links page doesn't properly validate for a scheme when a port is present. i.e. Entering `redirecting-to.com` does not pass validation (prevents me from Saving, I think due to lack of scheme), but `https://redirecting-to.com` and `redirecting-to.com:8581` do pass validation. `redirecting-to.com:8581` should not pass validation if I am understanding you correctly.
