### ISSUE TITLE
Favicon possible for every user page?

### ISSUE THREAD

**Issue by NoFloXx** [LinkStackOrg/LinkStack#655]
Hi,
I have several users on my LinkStack installation, which can then be used to access the respective pages.

The users have VIP status because of the verification hook.

What bothers me, however, is that you can only set the favicon for the entire instance.
Would there be a way to set the favicon for each user page separately?

Thanks in advance.

**Comment by JulianPrieber** [comment]
Custom favicons are fairly easy to implement, custom image storage however is.
Allowing users to use their profile picture as the favicon should be fairly easy.

If you want to request a feature like this, please add it here: https://github.com/orgs/LinkStackOrg/discussions/categories/feature-requests
