### ISSUE TITLE
Still not redirecting properly on install, and /skip not working either

### ISSUE THREAD

**Issue by aubreyz** [LinkStackOrg/LinkStack#675]
### LinkStack version

4.6.1

### Description

Noting issue https://github.com/LinkStackOrg/LinkStack/issues/354 (Setup failing between steps 3 and 4 on /db) which I don't think should have been closed since there was no solution for those facing the issue. None of the solutions work including the final comment in closure (as pointed out in the thread that does not redirect either)

After pressing next on https://links.domainxxx.co.uk/?3
I get to
https://links.domainxxx.co.uk/db

with response without any redirection
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

If I start again with
https://links.domainxxx.co.uk/skip
I get the same server error as above in immediate response so that's not a route out of it
Is there some other way to skip the setup

I have tried reinstalling from scratch several times (on different domains or subdomains) all with the same problem.
All on an Ionos server (I mention that because Ionos - a pretty big provider so may be coincidental - was mentioned above)

Going back to https://links.domainxxx.co.uk/ gets back to the start on the setup without problem

I just figured out that after /db
I can go manually to https://links.oboehannah.co.uk/?4
However if I fill that in
I get redirected to
https://links.oboehannah.co.uk/create-admin
with the same 404 again

Not sure where to go from here. Happy to work with you on debugging this on a real live instance

### Details about your system

PHP 8.2 Ionos hosting

### How to reproduce

See detailed discussion or try complete installation yourselves at https://links.oboehannah.co.uk/

### Possible Solution

None known - cannot install via any route including via /skip

**Comment by JulianPrieber** [comment]
Please provide your PHP error log for your instance.

**Comment by aubreyz** [comment]
> Please provide your PHP error log for your instance.

No idea where or how to get this.

**Comment by JulianPrieber** [comment]
Ask your hosting provider or look into your hosting provider's documentation.

**Comment by aubreyz** [comment]
> Ask your hosting provider or look into your hosting provider's documentation.

I would have to copy a php ini file into every one of dozens of folders in the install -0 not knowing what I am looking for. At least logging for php errors in the main root of the install shows no error lines at all. 

This is a straighforward untouched clean domain with a major hosting provider and an up to date php, and an straightforward install as a file copy. And I have sent you an instance of a non-working install (exactly as quite a lot of others are reporting) and offering to assist in working out why this is stopping people from using your software. 

I presumed you tried the link with the same outcome?

**Comment by aubreyz** [comment]
I'm closing this issue as I do not plan to expend more time on this package sadly,
