### ISSUE TITLE
"Open links in new tab" setting can't be activated

### ISSUE THREAD

**Issue by escuco** [LinkStackOrg/LinkStack#679]
### LinkStack version

4.7.0

### Description

I've updated my LinkStack installation to v4.7.0 via the integrated web updater. 

In the "Appearance" settings I'm able to switch "Open links in new tab" to enabled, but after clicking "save" the setting is disabled again.

I've tried Firefox and Chrome (Linux).

### Details about your system

PHP 8.1

### How to reproduce

- Click "Appearance"
- Enable "Open links in new tab"
- Click "Save"

**Comment by JulianPrieber** [comment]
I'll push a fix in a bit.

**Comment by JulianPrieber** [comment]
I pushed the fix to the existing release. To apply the changes update again.

To update again, edit your version.json and change the version to 4.6.1 and save.
On your admin panel, the option to update again should now appear.

**Comment by escuco** [comment]
Thank you, that worked for me!
