### ISSUE TITLE
Unable to modify login e-mail address of account.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [LinkStackOrg/LinkStack#684]
### LinkStack version

https://linksta.cc/

### Description

**https://github.com/orgs/LinkStackOrg/discussions/683**

> I am unable to modify/replace the e-mail address which I use to log in.

### Details about your system

https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-121.0-1.1.x86_64.rpm on cpe:/o:opensuse:tumbleweed:20240106.

### How to reproduce

Access https://linksta.cc/studio/profile or https://linksta.cc/studio/page.

**Comment by JulianPrieber** [comment]
This is a feature since version 0.1.
Admins can choose to disable this field, so only admins can change the email.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/684#issuecomment-1883385869

@JulianPrieber, does that mean that https://linksta.cc/ has disabled that option? If so, considering it's the official instance of the project, how does one request that their e-mail address be modified? Post a https://github.com/orgs/LinkStackOrg/discussions/new?category=general?

**Comment by JulianPrieber** [comment]
> > [#684 (comment)](https://github.com/LinkStackOrg/LinkStack/issues/684#issuecomment-1883385869)
> 
> @JulianPrieber, does that mean that https://linksta.cc/ has disabled that option? If so, considering it's the official instance of the project, how does one request that their e-mail address be modified? (Post a https://github.com/orgs/LinkStackOrg/discussions/new?category=general?)

That is correct, it is disabled on linksta.cc on purpose.
We normally expect you to create a new account and simply migrate your links.
If that is not an option for you, you can reach support on our contact page.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/684#issuecomment-1883396225

I'll do so. Thanks. However, @JulianPrieber, what's the benefit to disabling it?

**Comment by JulianPrieber** [comment]
There is no built-in logic for verifying an email after a change. The idea was always that if verification is enabled, an email is permanently bound to an account. Also, this would mess with social accounts a bit.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/684#issuecomment-1883396225

I've sent a message from s1hvpv+info=linkstack.org@rokejulianlockhart.anonaddy.com to info@linkstack.org.

> https://github.com/LinkStackOrg/LinkStack/issues/684#issuecomment-1883401333

@JulianPrieber, could I make an issue about that, then? Seems like having half-baked functionality for such an important aspect of account management might be a problem, especially since malicious actors on servers with this functionality enabled could register for an account with a trusted e-mail address and then change it to a non-trusted one.

**Comment by JulianPrieber** [comment]
> could I make an issue about that, then? Seems like having half-baked functionality for such an important aspect of account management might be a problem, especially since malicious actors on servers with this functionality enabled could register for an account with a trusted e-mail address and then change it to a non-trusted one.

I'm a bit confused... we do not allow changing the email to combat exactly this "account with a trusted e-mail address and then change it to a non-trusted one".
What you're describing is what is already implemented, so where is the issue?
