### ISSUE TITLE
403 After deleting link

### ISSUE THREAD

**Issue by trip1e** [LinkStackOrg/LinkStack#692]
### LinkStack version

v4.7.1

### Description

Page: /studio/links
Task: Delete link
Procedure: I press the DELETE (trash) button next to the link I want to delete.
What happens: Redirects to 403 - /deleteLink/907871310 - The link is not deleted

### Details about your system

PHP Version 8.0.30
--

System | Linux uvirt106 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64
-- | --
Build Date | Aug 7 2023 10:14:23
Build System | Linux bullseye 5.10.0-23-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27) x86_64 GNU/Linux
Configure Command | './configure' '--prefix=/usr' '--with-apxs2=/usr/bin/apxs2' '--with-config-file-path=/etc/php80/apache2' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--with-libdir=/lib/x86_64-linux-gnu' '--mandir=/usr/share/man' '--disable-debug' '--disable-rpath' '--disable-static' '--with-pic' '--with-layout=GNU' '--with-pear=/usr/share/php' '--enable-calendar' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-bcmath' '--with-bz2' '--enable-ctype' '--with-db4' '--with-gdbm=/usr' '--enable-intl' '--enable-exif' '--enable-ftp' '--with-gettext' '--enable-mbstring' '--enable-shmop' '--enable-sockets' '--with-zlib' '--with-kerberos=/usr' '--with-openssl=/usr' '--enable-mysqlnd' '--with-pdo-mysql' '--with-pdo-pgsql' '--with-pdo-dblib' '--with-mysqli' '--with-mhash' '--with-tidy' '--enable-soap' '--with-zip' '--without-mm' '--with-curl=/usr' '--enable-gd' '--with-jpeg' '--with-xpm=/usr/X11R6' '--with-webp' '--with-freetype' '--with-zlib-dir=/usr' '--with-ldap=/usr' '--with-imap=/usr' '--with-imap-ssl=/usr' '--with-unixODBC=shared,/usr' '--with-xsl=/usr' '--with-libxml' '--with-snmp=/usr' '--with-pgsql=/usr' '--with-iconv' '--enable-opcache' '--with-pspell=shared' '--with-sodium' '--with-enchant' '--with-gmp=shared' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu'
Server API | Apache 2.0 Handler
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc/php80/apache2
Loaded Configuration File | /etc/php80/apache2/php.ini
Scan this dir for additional .ini files | (none)
Additional .ini files parsed | (none)
PHP API | 20200930
PHP Extension | 20200930
Zend Extension | 420200930
Zend Extension Build | API420200930,NTS
PHP Extension Build | API20200930,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | enabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters | zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, convert.*, consumed, dechunk

### How to reproduce

Press the DELETE (trash) button next to the link I want to delete.

**Comment by JulianPrieber** [comment]
We need more help reproducing this. This has been reported 3 times so far. I'm assuming this is some issue with authentication.

**Comment by trip1e** [comment]
What can I do for you regarding this issue?

Dominik Kralik
mobile: +421 944 931 000
email: ***@***.***

**Comment by JulianPrieber** [comment]
> What can I do for you regarding this issue?

Best is a step-by-step setup guide how to reproduce the issue reliably, or if you were able to fix the issue documentation for that.

If I use a recent version and set it up either using the docker image or NGINX/Apache, I cannot reproduce this issue.
There has to be something causing this, we're just not sure what it is.

**Comment by p-collins** [comment]
Just to report I'm experiencing this as well, both delete and edit links results in 403 Forbidden. 

SQLite backend running on IIS non-production, everything is straight out the zip folder. Let me know if I can shared anything specific to help

**Comment by JulianPrieber** [comment]
Let me know if someone can edit the biosystem and run a debug file for me 👍

**Comment by JulianPrieber** [comment]
Please replace the file content of app/Http/Middleware/LinkId.php with this debug file:
https://gist.github.com/JulianPrieber/d5318ca83f09879f93a1092fea38bb8c

Then log in to your admin panel and try to delete a link.

**Comment by p-collins** [comment]
No worries, here's the output:

https://gist.github.com/p-collins/ca393afd5f19c447398e541d7be58902

**Comment by p-collins** [comment]
Confirmed fix for me at least.
