### ISSUE TITLE
Text block twice in the list

### ISSUE THREAD

**Issue by thibaultmol** [LinkStackOrg/LinkStack#698]
### LinkStack version

linksta.cc

### Description

I noticed that the 'text' block is shown twice when adding a new link on https://linksta.cc/studio/add-link

![Screenshot 2024-01-21 at 23-26-15 LinkStack](https://github.com/LinkStackOrg/LinkStack/assets/1010226/7adb35af-da1a-4683-bf2c-3c2843de2dbc)

### Details about your system

[whatismybrowser.com/w/TH2GTBE](whatismybrowser.com/w/TH2GTBE)
(Firefox 121 on Linux)

### How to reproduce

[https://linksta.cc/studio/add-link](https://linksta.cc/studio/add-link)
and choose 'select block'

**Comment by JulianPrieber** [comment]
Thank you for reporting this. 
Seems to appear on older instances. Not sure why.
A fix is probably on the way, this needs some testing first.

For everyone experiencing this issue, this does not seem to impact the normal function in any way and can be ignored for now.

**Comment by JulianPrieber** [comment]
Fixed with `v4.8.1-beta-4`.
