### ISSUE TITLE
linkstack page contains DOS path separatoprs

### ISSUE THREAD

**Issue by alexlehm** [LinkStackOrg/LinkStack#708]
### LinkStack version

de.linkstack.cc

### Description

I am using de.linksta.cc with the CloudyStorm theme and the resulting page contains a few paths with backslash as path separator, this works fine in a regular browser but confuses wget for example a lot

the path for some assets starts with /\/ and the path for icon assets is e.g. /icons\....svg

### Details about your system

this is showing on the de.linksta.cc instance

### How to reproduce

create a new user with the CloudyStorm theme, add a few links, the resulting page will contain the backslashes

### Possible Solution

I assume this is in the theme and should replace the \ by / in all cases

### Additional Context

i have checked the page with another template and the same errors show, so its in the main project and not in the specific template

**Comment by JulianPrieber** [comment]
Version 5.0 should address this.
