### ISSUE TITLE
Dashboard / Admin becomes gradually unresponsive

### ISSUE THREAD

**Issue by misterd4n** [LinkStackOrg/LinkStack#719]
### LinkStack version

4.7.4

### Description

Installed the latest version on my webhosting server. Managed to create my links. Gradually, as i was working on adding the links, the dashboard / admin gradually took longer and longer to load and redirect to the point where it became completely unresponsive.

Tried reinstalling a few times, to face the same problem each time. All dependencies were checked and met when I did the install.

I have no idea what might cause this and where to start to troubleshoot the problem. If anyone could point me to the right direction, that would be really appreciated. 

### Details about your system

Linux
Apache 2.4.58
PHP version 8.2

### How to reproduce

Fresh install.

**Comment by talheim-it** [comment]
Have you tried with nginx and php8.2-fpm?

I Don't have any troubles.
