### ISSUE TITLE
adding  Email Address Block not adding anything

### ISSUE THREAD

**Issue by rahilarious** [LinkStackOrg/LinkStack#722]
### LinkStack version

4.7.5

### Description

working in 4.7.2 though

### Details about your system

docker

### How to reproduce

deploy latest docker image, upgrade to 4.7.2 and then add email block

### Possible Solution

https://github.com/LinkStackOrg/LinkStack/compare/v4.7.2...v4.7.5

**Comment by JulianPrieber** [comment]
Fixed in latest beta

**Comment by elk2210** [comment]
Bug is still present on 4.7.6. At least for me.

**Comment by JulianPrieber** [comment]
Fixed in `v4.7.7-beta-1`
