### ISSUE TITLE
Database connection - non docker

### ISSUE THREAD

**Issue by eightsixeight** [LinkStackOrg/LinkStack#747]
### LinkStack version

latest

### Description

getting 

previous exception] [object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: PRAGMA foreign_keys = ON;) at /var/www/xyz/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]

### Details about your system

php 8.1 
sqlite 
mysql
apache

### How to reproduce

load initial page.

### Possible Solution

figure why it's not finding my apache sdo_sqlite nor mysql even if enabled

**Comment by lastsamurai26** [comment]
Hey, 

Can you show me your php ini or your installed modules for php ?

**Comment by eightsixeight** [comment]
fixed that, by removing all and redoing the pdo parts, but i get an issue with route controllers not working and resulting on a 404 on all ,
