### ISSUE TITLE
Copy link issue

### ISSUE THREAD

**Issue by Hanhne9** [LinkStackOrg/LinkStack#748]
### LinkStack version

4.7.7

### Description

When I copy an URL, it saves double link like this https://www.tumblr.com/blogcuahanh/745811259421753344?source=share

### Details about your system

PHP 8.1

### How to reproduce

I don't know

**Comment by JulianPrieber** [comment]
Copy where?
And how is this "https://www.tumblr.com/blogcuahanh/745811259421753344?source=share" a "double link" exactly?

**Comment by Hanhne9** [comment]
> Copy where? And how is this "https://www.tumblr.com/blogcuahanh/745811259421753344?source=share" a "double link" exactly?

Yep

**Comment by JulianPrieber** [comment]
Huh?

**Comment by Hanhne9** [comment]
> Huh?

Can you fix it

**Comment by JulianPrieber** [comment]
Please provide proper documentation in form of a video or an exact guide how to reproduce this issue.

**Comment by Hanhne9** [comment]
> Vui lòng cung cấp tài liệu thích hợp dưới dạng video hoặc hướng dẫn chính xác về cách tái hiện vấn đề này.


Uploading Screenrecorder-2024-03-24-20-43-06-358.mp4…
