### ISSUE TITLE
Matrix Synapse usernames are not valid links

### ISSUE THREAD

**Issue by pscriptos** [LinkStackOrg/LinkStack#755]
Hello everyone,
First of all, thanks for this great software. It was important to me to use open source software and I found it with your software.

I have noticed that I cannot maintain a matrix user name.
I only get the message that I should please enter a valid URL.

The Message:
![grafik](https://github.com/LinkStackOrg/linkstack-docker/assets/49373047/7b6aaaff-5643-45ab-b8a5-dffbe6720403)

My Username in Matrix:
![grafik](https://github.com/LinkStackOrg/linkstack-docker/assets/49373047/c61b3e46-56e9-4846-a3b0-392c7fe9e432)

Is there a way to fix this?

Thank you for your support. You guys are great!

Best regards, Patrick

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/755#issue-2235957854

@pscriptos, that's because that's not a URI. Use https://github.com/matrix-org/matrix-spec-proposals/blob/f295e828dc3107260a7979c40175442bf3a7fdc4/proposals/2312-matrix-uri.md?plain=1#L71 or https://matrix.to/.
