### ISSUE TITLE
Line breaks in display name are too large.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [LinkStackOrg/LinkStack#759]
### LinkStack version

https://linksta.cc/

### Description

> ![Screenshot_20240417_143133](https://github.com/LinkStackOrg/LinkStack/assets/42837531/2441c29b-7b97-4325-a440-e3114a7dabcd)

### Details about your system

<table><tr>
	<th>OS</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td></tr></table>

### How to reproduce

Visit https://linksta.cc/studio/links or https://linksta.cc/@RokeJulianLockhart.

### Possible Solution

Make the line breaks render like regular enlarged text's does. I dunno what CSS you're using to style it, but check that you're using `em` instead of static `px` definitions.

**Comment by JulianPrieber** [comment]
We are using upstream [littlelink](https://github.com/sethcottle/littlelink) as the base for our styling.
This may be resolved using a custom theme.

We will continue using the current styling format for now, until we replace it.
When we switch our layout system, this will be revised along with some other styling and spacing issues that the current layout has.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/759#issuecomment-2408482499

Glad to hear, @JulianPrieber. I've filed https://github.com/sethcottle/littlelink/issues/127#issue-2583186450 in the hope that it might be fixed upstream to reduce your workload.

After all, the line height should be reduced in proportion to the amount that the text has increased from 1 em.
