### ISSUE TITLE
Links no longer copy as argument of permalink.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [LinkStackOrg/LinkStack#760]
### LinkStack version

https://linksta.cc/

### Description

Links used to copy as something similar to `https://linksta.cc/going/${LinkID}?${URI}`, rather than the stored URI. Now, I have to manually craft them by visiting `https://linksta.cc/studio/edit-link/${LinkID}`.

### Details about your system

<table><tr>
	<th>OS</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td>
</tr></table>

### How to reproduce

Visit https://linksta.cc/studio/links or https://linksta.cc/@RokeJulianLockhart.

### Possible Solution

Expose the ability to explicitly copy a permalink with the URI as an argument in the studio (better than before) and/or automatically include the permalink in that format when accessing a link (same as before).

### Additional Context

In the event that this was deliberate, I've filed https://github.com/orgs/LinkStackOrg/discussions/756#discussion-6509383 too.

**Comment by JulianPrieber** [comment]
As of version 4.7.0 this is the intended behavior.
The next major revision is planned to implement an internal link-shortener type system.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/LinkStackOrg/LinkStack/issues/760#issuecomment-2408478520

@JulianPrieber, obfuscating the eventual URI unfortunately means that the new implementation falls victim to [link rot](https://en.wikipedia.org/w/index.php?title=Link_rot&oldid=1249151235#:~:text=Link%20rot%20(also%20called%20link%20death%2C%20link%20breaking%2C%20or%20reference%20rot)%20is%20the%20phenomenon%20of%20hyperlinks%20tending%20over%20time%20to%20cease%20to%20point%20to%20their%20originally%20targeted%20file%2C%20web%20page%2C%20or%20server%20due%20to%20that%20resource%20being%20relocated%20to%20a%20new%20address%20or%20becoming%20permanently%20unavailable.):

> Link rot (also called link death, link breaking, or reference rot) is the phenomenon of [hyperlinks](https://en.wikipedia.org/wiki/Hyperlink) tending over time to cease to point to their originally targeted [file](https://en.wikipedia.org/wiki/Computer_file), [web page](https://en.wikipedia.org/wiki/Web_page), or [server](https://en.wikipedia.org/wiki/Server_(computing)) due to that resource being relocated to a new address or becoming permanently unavailable.
