### ISSUE TITLE
the page view on a mobile chrome is really horrible, how to fix this?

### ISSUE THREAD

**Issue by xyychenchen** [LinkStackOrg/LinkStack#763]
### LinkStack version

4.7.7

### Description

i open the linkstack page on my iphone12 pro chrome browser, 
The connected button is not centered and can be dragged left or right. Additionally, the background of the entire theme can be scaled down, resulting in a black background as shown in the image. Furthermore, the avatar, name, description, and buttons on the entire linkstack page are not aligned. Is this a page that can only be opened on a computer web browser, or is there a need to adjust settings for mobile devices? I seem to have not found the settings for mobile devices.
![1a77d4c49412b4e3f6fc5c656250ee6](https://github.com/LinkStackOrg/LinkStack/assets/142563518/9d032a03-b20f-4707-9187-86e3de3a7b6f)

### Details about your system

iphone12 pro

### How to reproduce

open it on a mobile web browser

**Comment by talheim-it** [comment]
@xyychenchen I made a pull request but it was denied for adopting points. But you can check it. I plan to fix it as soon as I find the time beside my other projects for it. 

You can see it in the project related issues.

**Comment by xyychenchen** [comment]
thank you my friend, it is very nice of you
