### ISSUE TITLE
Predefined Site drop-down list not visible

### ISSUE THREAD

**Issue by MacBadger** [LinkStackOrg/LinkStack#771]
### LinkStack version

4.7.7

### Description

When adding a predefined site block, the drown down for selecting the site is visible, but the text in the lists is not.
When selecting one randomly (as you can't see the list) it is still invisible.
When saved, and editing, you can see the active one, but the other in the list are still invisible.

Same across all themes - including the standard themes.
Light/Dark doe not make a change.

Happened since upgrade to 4.7.7 (did jump a few versions however).

### Details about your system

Debian, PHP 8.2.14, apache

### How to reproduce

.

**Comment by MattDevTec** [comment]
I have thoroughly tested with all kinds of different settings, and I also cannot reproduce

**Comment by MacBadger** [comment]
i'm on regular install still and still have same issue.
all updated.
Tried inspecting CSS etc. Nothing. No weird white text, or as i can tell anything over top,
best i can fathom is, the list is being generated, but not being brought through, with text- **just the option class name, no actual text** to populate it.
Not fathomed where this would come from though
