### ISSUE TITLE
Page URL incorrectly states username is when it contains a period/invalid character

### ISSUE THREAD

**Issue by taivlam** [LinkStackOrg/LinkStack#786]
### LinkStack version

4.8.0

### Description

When selecting a username on the Sign Up page, the text field for Page URL will erroneously report that a username is taken when it actually contains an invalid character (such as period/`.`) on the main LinkStack instance.

### Details about your system

Linux/Manjaro Unstable with Brave Browser version `1.66.115-1` on the main LinkStack instance `linksta.cc`.

### How to reproduce

Suppose `multipartusername` is the desired base form of the username and is not taken.

Using a pure alphanumeric `multipartusername`, hyphen separators like `multi-part-username`, or underscore separators like `multi_part_username` is valid.

However, `multipart.username` is invalid, since periods are not allowed.  However, the form reports with client-side form message that says:
> That username is already taken

### Possible Solution

During the sign up process, if an invalid character is used for a username, then the form should tell the user that an invalid character has been used; and also the user should be told what characters are valid in usernames.

**Comment by JulianPrieber** [comment]
With our current system this is the expected behaviour

**Comment by JulianPrieber** [comment]
This system will be replaced in the next major revision.

Until then this will be the intended behavior.
