### ISSUE TITLE
Cannot save LinkStack favicon in KeePassXC (on `linksta.cc`)

### ISSUE THREAD

**Issue by taivlam** [LinkStackOrg/LinkStack#796]
### LinkStack version

4.8.0

### Description

I cannot save the LinkStack favicon when I use either `linksta.cc` or `linksta.cc/login` as the URL in KeePassXC.

The website favicon downloading doesn't work, and KeePassXC gives an error message of "Unable to fetch favicon."

The icon for my LinkStack entries in KeePassXC currently look like this:
![pic1](https://github.com/LinkStackOrg/LinkStack/assets/47955724/39c68fe5-21a6-4d70-8c4a-4cb7a7c24b4e)

### Details about your system

* Browser: Brave version `1.67.119`
* OS: Manjaro Unstable
* Main LinkStack instance `linksta.cc`
* KeePassXC version `2.7.9-1`

### How to reproduce

1. Try to save a URL's favicon via KeePassXC, as described in KeePassXC's [documentation](https://keepassxc.org/docs/KeePassXC_UserGuide#_icons).
2. KeePassXC is unable to save the favicon, no matter if the checkbox is checked on or off in: Settings > Security > Privacy > "Use DuckDuckGo service to download website icons".

### Possible Solution

If there is a successful solution, I expect KeePassXC to save the favicon successfully so that it looks like the favicon when I navigate to LinkStack in Brave Browser:
![pic2](https://github.com/LinkStackOrg/LinkStack/assets/47955724/b4e66d31-1173-4488-a0c2-ed148272d636)

### Additional Context

I apologize in advance if this is off-topic for LinkStack, but I figured it was more direct for me to troubleshoot with LinkStack rather than to troubleshoot with KeePassXC.

**Comment by lastsamurai26** [comment]
This looks more like an error on the part of KeePassXC, since I don't use KeepassXC myself, the question here would be how KeePassXC obtains the favicons.
The website favicon is located at Https://linksta.cc/assets/linkstack/images/logo.svg
Now the question is where KeePass tries to download this, otherwise you can simply download this file yourself and upload it manually.
