### ISSUE TITLE
419 Error after signin

### ISSUE THREAD

**Issue by jbugel-lol** [LinkStackOrg/LinkStack#799]
### LinkStack version

4.2.3

### Description

When I want to add a link, it prompts me to log in, after I log in, I get a 419 Error

### Details about your system

Debian 12
PHP 2.0
installed via Dockge
Nginx Proxy Manager - Reverse Proxy

### How to reproduce

Go to "Add Link"
Login
Error

### Additional Context

<img width="969" alt="image" src="https://github.com/user-attachments/assets/ce070a4d-e2f1-4b86-85c5-80c8929c073d">

**Comment by JulianPrieber** [comment]
PHP 2.0?

**Comment by jbugel-lol** [comment]
atleast it says in the advanced config, oh nvm its the used php version, idk the php version cause linkstack installed it with it

**Comment by jbugel-lol** [comment]
Oh. I didn't see an update was available, that fixed it, sorry
