### ISSUE TITLE
Custom link always point to the same page

### ISSUE THREAD

**Issue by nekosheen** [LinkStackOrg/LinkStack#806]
### LinkStack version

4.8.1

### Description

The link given to the "Custom Link" element:
1. does not persist after save
2. is automatically replaced by the URL of the linkstacks page

### Details about your system

Using the docker instance

### How to reproduce

As a logged in user

-> Go to `/studio/add-link`
-> Click on `Select Block`
-> Select `Custom Link`
-> Fill the title with "Google"
-> Fill the URL with "https://google.com"
-> Click Save

Go to your page and...
Admire how the link to Google is just a link to the page now and if you go back in to modifiy the URL, you'll see that yours did not persist in the field (nor the database I guess?).

**Comment by lastsamurai26** [comment]
Thx for Reporting 

which Version you are using from 4.8.1 ?

**Comment by nekosheen** [comment]
@lastsamurai26 
I just run the docker container and the other morning it asked me if I wanted to update to 4.8.1 in the UI so I clicked update
I don't really understand your question I'm afraid, how can I check `Which version you are using from 4.8.1` ?

**Comment by lastsamurai26** [comment]
can you check in you .env the value JOIN_BETA?

but nevertheless i'll have a look why this is so. in the 4.8.0 which is currently productive and released it works. 

4.8.1 is currently still beta

**Comment by nekosheen** [comment]
Ooooo that is possible, I did enable beta and installed and applied the 4.8.1-something then disabled the beta and I thought it was back on a production release since it just showed 4.8.1

Is there any way to properly downgrade to 4.8.0 - knowing that I'm using Docker ?

**Comment by lastsamurai26** [comment]
uff -> only revert it via Backup

**Comment by nekosheen** [comment]
Well that will teach me 😿

**Comment by lastsamurai26** [comment]
you can try to upload the last release and overwrite all files, this can work, but unfortunately it can always go wrong, as with any other software
