### ISSUE TITLE
composer update command fails due to dependency conflict with spatie/laravel-backup and laravel/framework

### ISSUE THREAD

**Issue by nyxb** [LinkStackOrg/LinkStack#816]
### LinkStack version

4.8.0

### Description

**Issue Description**:
I encountered a problem while trying to run `composer update -vvv` as part of the contribution process.

### Steps to Reproduce:

1. Fork the repository and clone it to your local machine.
2. Open a terminal in the repository folder.
3. Run `composer update -vvv`.

### Expected Behavior:
The `composer update` command should resolve dependencies and update the packages.

### Actual Behavior:
The command fails due to a conflict between the `spatie/laravel-backup` package and the `laravel/framework`. Here's the relevant part of the error message:

```
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Root composer.json requires spatie/laravel-backup ^8.17 -> satisfiable by spatie/laravel-backup[v8.x-dev].
    - Conclusion: don't install laravel/framework v9.52.16 (conflict analysis result)
    - spatie/laravel-backup v8.x-dev requires illuminate/support ^10.10.0|^11.0 -> satisfiable by illuminate/support[v10.x, v11.x].
```

### Analysis:
It seems like the `spatie/laravel-backup` package is requiring versions of `illuminate/support` that are incompatible with the current `laravel/framework` version (`v9.x`). Specifically, `spatie/laravel-backup` v8.x-dev is compatible only with Laravel 10.x or 11.x.

### Possible Solutions:
- **Option 1**: Update the Laravel version in `composer.json` to Laravel 10 or 11 to resolve the version conflict.
- **Option 2**: Downgrade the `spatie/laravel-backup` package to a version that is compatible with Laravel 9.
  
### Environment:
- Laravel Framework: v9.52.x
- spatie/laravel-backup: v8.x-dev

### Additional Context:
This issue prevents me from proceeding with the local setup and making the necessary code changes.

### Details about your system

MacOS

### How to reproduce

only clone

**Comment by JulianPrieber** [comment]
**As a workaround:**

`composer install` should work using the current dependency versions.

Alternatively, you could try using the Laravel 10 version: https://github.com/LinkStackOrg/LinkStack/tree/laravel-10

**Comment by nyxb** [comment]
@JulianPrieber 

The Laravel 10 version is unfortunately 72 commits behind and based on version 4.7.3. While `composer install` does work, I'm wondering why the `CONTRIBUTING.md` states:

“Pull requests are the best way to propose changes to the codebase (we use [Github Flow](https://guides.github.com/introduction/flow/index.html)). We actively welcome your pull requests:

1. Fork the repo and create your branch from master.
2. Clone your repository to your local machine.
3. Open a terminal window in that folder.
4. Run these commands:
   - `composer update -vvv`
   - `php artisan migrate`
   - `php artisan db:seed`
   - `php artisan db:seed --class="AdminSeeder"`
   - `php artisan db:seed --class="PageSeeder"`
   - `php artisan db:seed --class="ButtonSeeder"`
5. Move the folder into a local web server (make sure you double-check the [requirements](https://linkstack.org/docs/d/installation-requirements/)).
6. Now edit any files you want to change.
7. Commit your changes to your forked repository.
8. Issue that pull request!”

Additionally, the `release.yml` also runs `composer update --no-scripts`. How can these steps described in the `CONTRIBUTING.md` work when `composer update --no-scripts` is used in the release pipeline? 

Is it possible that certain scripts or steps are excluded by the `composer update` options in the release pipeline, which might explain the discrepancies?

**Comment by nyxb** [comment]
The issue seems to be with the package spatie/laravel-backup: "^8.17". Changing it to spatie/laravel-backup": "^8.0"
