### ISSUE TITLE
custom theme doesn't work on linkstack

### ISSUE THREAD

**Issue by darongtt** [LinkStackOrg/LinkStack#819]
### LinkStack version

4.8.0

### Description

I wanna upload new theme, and when I wanna do it through background, it keep said "413 Request Entity Too Large", even if I modified the nginx conf file and php.ini file and enlarge the file size, so I change another way to upload it, I just directly download the theme zip file and then upload to the server to finalshell, and i upload it to /var/www/html/linkstack/theme and then I just unzip it, and I select it and it keep showing this below 
![image](https://github.com/user-attachments/assets/a670814f-124e-4189-ac2f-b0f665762a5b)
it said this line @if(theme('enable_custom_code') == "true" and theme('enable_custom_head') == "true" and env('ALLOW_CUSTOM_CODE_IN_THEMES') == 'true')@include($GLOBALS['themeName'] . '.extra.custom-head')@endif occurs error

### Details about your system

php 8.2
I tried debian 11 and ubuntu 22.04 this situation occurs anyway

### How to reproduce

i use it like a normal user and it produce the problem

**Comment by xyychenchen** [comment]
plz check my page https://kkberry.com and you can see the details of the error, basically for each custom upload theme this error will occur, plz help me thank you

**Comment by JulianPrieber** [comment]
Remove the version number from stargazer-1.9.
Theme folders cannot contain dots.

Please rename the folder to just stargazer.

**Comment by xyychenchen** [comment]
> Remove the version number from stargazer-1.9. Theme folders cannot contain dots.
> 
> Please rename the folder to just stargazer.

oh my god, that simple?    i love you man, you reply iis so intime

**Comment by xyychenchen** [comment]
it really kills me to think why is that

**Comment by xyychenchen** [comment]
> When loading the files the dots indicate the directory structure. Directory names are separated by dots. It tried to lead your theme from the "4" directory in your theme which doesn't exist.

yes you are right, and julian one more questions, i just lose my access to my dashboard, mine is a php file, and when i open the page with a new laptop and try to  login in the /login url, after i input the user pw inforamtion it redirect to the linkstack page, but not dashboard page, and i do not see a admin bar above the linkstack page, how to fix this
