### ISSUE TITLE
Running the update to v4.2.3 deletes all your data

### ISSUE THREAD

**Issue by renderghost** [LinkStackOrg/LinkStack#822]
### LinkStack version

4.2.2

### Description

I click on the bell and run the update.

All my user accounts and data disappears immediately. 

### Details about your system

Docker version on Render.com

### How to reproduce

I click on the bell and run the update.

All my user accounts and data disappears immediately.

**Comment by renderghost** [comment]
I tried it again and realised that when I run the update, the initial startup runs. I can't tell if the data has been deleted or not at that stage. I went through this the first time thinking it was part of the update, and I guess I deleted all the data doing that.

(I've just started using is, had just completed adding all my links, saw the update, thought it was good to run it, and then reset everything.)

**Comment by MattDevTec** [comment]
Do you happen to have made a backup when you updated? 

I will have a look myself with a test instance to see if thats the case for me as well.

**Comment by renderghost** [comment]
Hi

Sadly not. I had literally just set up the LinkStack for the first time.
It's all good. Wasn't loads of work for me to redo, but wanted to let you
know.

**Comment by JulianPrieber** [comment]
This may be more of a docker issue.
I am not aware of something like this happening before. We test each release for issues like this, and I haven't been able to reproduce this behavior.

Perhaps your setup is missing persistent storage?

@renderghost are you able to replicate this issue?

**Comment by MattDevTec** [comment]
@JulianPrieber I have also tested and have not replicated. Maybe automatic backups were turned off causing this?

**Comment by JulianPrieber** [comment]
> @JulianPrieber I have also tested and have not replicated. Maybe automatic backups were turned off causing this?

@MattDevTec on the contrary, depending on the hosting solution automatic backups sometimes cause issues, but nothing like this.

---

I'm closing this issue for now, should anyone encounter something similar, please report your findings [here](https://github.com/LinkStackOrg/linkstack-docker/issues).

When hosting LinkStack on Docker, make sure you have persistent storage enabled, see: [this section](https://github.com/LinkStackOrg/linkstack-docker/issues).
