### ISSUE TITLE
Can you make a docker version with Chinese language? I pulled it and there is no Chinese language

### ISSUE THREAD

**Issue by kele812** [LinkStackOrg/LinkStack#839]
### LinkStack version

4.8

### Description

Can you make a docker version with Chinese language? I pulled it and there is no Chinese language
thank you

### Details about your system

debian11

### How to reproduce

Can you make a docker version with Chinese language? I pulled it and there is no Chinese language

**Comment by lastsamurai26** [comment]
You can create your own language if it not included 

but normally there shuould be a zh or zc-tw language please check the settings 

admin -> Config --> Scroll complete in the bottom of the site

**Comment by kele812** [comment]
![image](https://github.com/user-attachments/assets/22827128-da26-45ea-a40e-1d7dece2ad25)
No Chinese language
I installed it using docker

**Comment by lastsamurai26** [comment]
Can you show me your version ?

**Comment by kele812** [comment]
I don't know where to look for my version, thanks for your help

**Comment by kele812** [comment]
Thanks for your help. After the upgrade, Chinese is available. Thank you!

**Comment by lastsamurai26** [comment]
> Thanks for your help. After the upgrade, Chinese is available. Thank you!

no problem, but i will check why is docker not downloading the lastest version of linkstack
