### ISSUE TITLE
Auto-Update from 4.2.3 -> 4.8.0 doesn't work

### ISSUE THREAD

**Issue by kollegahd** [LinkStackOrg/LinkStack#840]
### LinkStack version

4.2.3

### Description

The auto-update terminates each time with a timeout.

https://flareapp.io/share/W7zvb6v7

### Details about your system

I use the official docker-compose file:
https://github.com/LinkStackOrg/linkstack-docker

### How to reproduce

Just Auto Update from 4.3.2 to 4.8.0 with a docker container created via the docker-compose from here: https://github.com/LinkStackOrg/linkstack-docker

**Comment by lastsamurai26** [comment]
it seams that the apache webserver runs into a php timeout  becouse of the slow network connection 
you can make the update yourself
Download this packege 
https://github.com/LinkStackOrg/LinkStack/releases/download/v4.8.0/update.zip
and override your folder with this one, please make a backup before. 

I tried it several times and a can't reproduce it, after which time do you get this messege ?

**Comment by kollegahd** [comment]
I get it after 20 seconds

**Comment by kollegahd** [comment]
updating manually worked for me

**Comment by kollegahd** [comment]
So far everything is working, but I noticed the following in version 4.8.0: The predefined site selection list is there and works (you can select something there), but no text is displayed.
![Uploading Screenshot 2024-11-04 190457.png…]()

**Comment by kollegahd** [comment]
I was able to solve the problem myself. It was an error in the installation.

**Comment by klinkeye** [comment]
> I was able to solve the problem myself. It was an error in the installation.

Can you elaborate what you did to resolve it?

**Comment by kollegahd** [comment]
> > I was able to solve the problem myself. It was an error in the installation.
> 
> Can you elaborate what you did to resolve it?

After I had updated manually, the new database file only had read rights and no write rights.
I changed the rights and now it works.
