### ISSUE TITLE
Update to 4.8.1 not complete?

### ISSUE THREAD

**Issue by nesges** [LinkStackOrg/LinkStack#847]
### LinkStack version

4.8.0

### Description

I just updated our installation using the integrated updater in automatic mode. It confirms a successful update and I see severeal modifications in the filesystem, but the admin dashboard still shows v4.8.0 and offers the update to v4.8.1. Not sure if really succesful or just hasn't bumped the version number.

Here's what's changed on the fs:
```
root@oghma:/var/www/apache2/my.pnpde.social# find . -mmin -10
./database
./database/database.sqlite
./storage/logs/laravel.log
./storage/framework/cache/data/be/0b
./storage/framework/cache/data/be/0b/be0b554cca27bcdbd8fe0358cadfed8a1ea64245
./storage/framework/cache/data/78/98
./storage/framework/cache/data/78/98/789805a71beeba7fa8dd4c3a41b16cba21180cff
./storage/framework/views
./storage/framework/views/8145951f9f78e75191a1d63c596771075f30e67d.php
./storage/framework/views/47ce8763aa8611a57cd6171d18af12e5a8bb8ebb.php
./storage/framework/views/876c5589cac5811916f560522d6c851416ab23c0.php
./storage/framework/sessions
./storage/framework/sessions/A6w83HFFtBTYXBk8jTt7mau9UveCBBe6iJkF10Eo
./storage/app
./storage/app/self-updater-new-version
./resources/views/components/pre-update.blade.php
./backups
./backups/updater-backups
./backups/updater-backups/CK5VYhzQBr5eHsNX-2024-11-25-15-25-12.zip
./backups/updater-backups/qDqQEFkDI0td8c9M-2024-11-25-15-21-54.zip
./.env
```

### Details about your system

```
# uname -a
Linux oghma 5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# php -version
PHP 8.1.2-1ubuntu2.19 (cli) (built: Sep 30 2024 16:25:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.19, Copyright (c), by Zend Technologies
```

### How to reproduce

1.
![image](https://github.com/user-attachments/assets/7efe70c9-a1e0-4fc7-9874-2c30f8a27e3a)

2.
![image](https://github.com/user-attachments/assets/a8ce550d-53ac-422c-b829-6969f7ed3352)

3.
![image](https://github.com/user-attachments/assets/5d76a94d-a4de-49e3-b4e1-0703e7f198eb)

4.
![image](https://github.com/user-attachments/assets/cd7a3c1f-29d1-4a5e-a72a-49a0aae905af)

**Comment by MattDevTec** [comment]
Please try updating to v4.8.2. this seems to have resolved it according to my testing

**Comment by nesges** [comment]
That did the trick! The update to 4.8.2 worked. Thank you!
