### ISSUE TITLE
Bluesky page icon is invisible

### ISSUE THREAD

**Issue by saaaauce** [LinkStackOrg/LinkStack#850]
### LinkStack version

4.8.2

### Description

The page icon for Bluesky doesn't show up. In its place in the settings there is an icon alternating between ! and ?, see:

![image](https://github.com/user-attachments/assets/35d5b0f2-d266-4a9b-9e90-522c70b8cf94)

On the linkstack page/profile the link to the bluesky page exists and is clickable but there is no icon.
![image](https://github.com/user-attachments/assets/2c45fccf-0e8a-4517-ac5a-d2d282d0af22)

The icon svg is present in the assets/linkstack/icons folder and when adding Bluesky as a link instead of a page icon the icon displays properly:
![image](https://github.com/user-attachments/assets/ae1f3f8f-a7bf-4251-a71a-41ef760933d9)

### Details about your system

Linkstack docker running on Unraid 6.12.13

### How to reproduce

Attempt to add a page icon for Bluesky.

**Comment by JulianPrieber** [comment]
Fixed in `v4.8.4-beta-4`
