### ISSUE TITLE
vCard not saving information

### ISSUE THREAD

**Issue by tobsowo** [LinkStackOrg/LinkStack#852]
### LinkStack version

v4.8.3-beta-4

### Description

When a vCard is created, only the name is saved every other information is discarde

### Details about your system

PHP Version 8.2.7

### How to reproduce

Create a vCard link and save

**Comment by lastsamurai26** [comment]
can't reproduce is. 

can you install the lastet main version

**Comment by JulianPrieber** [comment]
Does the information persist when editing the vCard?

**Comment by tobsowo** [comment]
@lastsamurai26 I was on the latest main before using beta and it is the same.
@JulianPrieber yes, I have edited a couple of times and it does not save the data except for the first name and surname.

**Comment by tobsowo** [comment]
I just tried creating a new vCard and it is still same experience.
