### ISSUE TITLE
Bluesky icon missing due to old version of FontAwesome

### ISSUE THREAD

**Issue by stuartf** [LinkStackOrg/LinkStack#854]
### LinkStack version

4.8.3

### Description

The bluesky icon doesn't render.

### Details about your system

Running the docker image on Debian.

### How to reproduce

Launch the docker version of linkstack and upgrade to the latest version to get 4.8.3, go to /studio/links and scroll to the bottom to add a bluesky `Page Icon` note that the icon is missing here and on the rendered page.

### Possible Solution

I was able to fix this on my local install by upgrading FontAwesome to the latest version as described in #539

**Comment by MattDevTec** [comment]
Which is the version you updated to?

In have seen the BlueSky icon is certainly missing, I will look to make a pull request to fix that. 

![image](https://github.com/user-attachments/assets/de80cc24-6a3c-448d-90d2-8da2138b5754)

**Comment by stuartf** [comment]
I used FontAwesome 6.7.1 to fix it locally.

**Comment by MattDevTec** [comment]
I assume you moved fontawesome.js and fontawesome.css with the same file name in the latest version locally?

**Comment by stuartf** [comment]
I copied the `webfonts` directory to `assets/webfonts` and `studio/webfonts`
and `all.min.js` from the `js` directory to `assets/external-dependencies/fontawesome.js`
and `all.min.css` from the `css` directory to `assets/external-dependencies/fontawesome.css`

**Comment by MattDevTec** [comment]
@stuartf This was just fixed with the latest beta update!
