### ISSUE TITLE
Can't exit impersonation

### ISSUE THREAD

**Issue by shidevil** [LinkStackOrg/LinkStack#872]
### LinkStack version

4.8.4

### Description

The latest version 4.8.4 is unable to exit impersonation. Even if the user is verified. 

### Details about your system

Ubuntu, php 8.2

### How to reproduce

1. In ID 1 admin account click -> impersonate on any account
2. You will be stuck in this account no matter what.

### Possible Solution

Editing the sqlite/mysql of user ID 1 auth-as value to 1. Will return.

**Comment by lastsamurai26** [comment]
This error should already be fixed. 

You may have to completely rebuild your instance with backup etc. 
Have you always carried out an update or have you completely rebuilt the instance in the meantime? 
Do you have opcache active?  

Can you try this with a new installed instance ?

**Comment by shidevil** [comment]
Okay i rebuild with backup and it works now! Thank you

**Comment by lefthandens** [comment]
Hi, I'm running linkstack with docker after updating to 4.8.4 the impersonate doesn't works now, how can i rebuild the instance with backup in docker?

**Comment by payphone101** [comment]
4.8.4~ynh1 here, still stuck in impersonation mode? Isn't there an un-impersonate button somewhere instead that we could click?
