### ISSUE TITLE
502 Bad Gateway Error when verifying email on linksta.cc

### ISSUE THREAD

**Issue by JackJack8ack** [LinkStackOrg/LinkStack#875]
### LinkStack version

n/a

### Description

I created a new account on the linksta.cc instance. When I try to verify my email, I get a 502 Bad Gateway Error and the verification does not go through.

### Details about your system

Windows 11 23H2
Firefox 133

### How to reproduce

Create a new account, open your email client to verify email address

### Additional Context

![Screenshot 2024-12-20 203101](https://github.com/user-attachments/assets/9cfc5310-76af-45c5-8eac-44d57c958efd)

**Comment by MattDevTec** [comment]
I will take a look to replicate this issue.

**Comment by MattDevTec** [comment]
![image](https://github.com/user-attachments/assets/bd5f8ee8-15cc-479d-903d-2fd65d75b553)
This error is also the same for me.

**Comment by JackJack8ack** [comment]
good news, it started working again!

**Comment by PhieF** [comment]
@tvx-matt Hi there, I'm having the same issue again
