### ISSUE TITLE
Not working with Traefik

### ISSUE THREAD

**Issue by linuxuser332** [LinkStackOrg/LinkStack#876]
### LinkStack version

latest

### Description

I have followed the guide on the docs for using behind a Traefik container.  I have set all the appropriate labels, but the Traefik container says that it is filtering the linkstack container because it unhealthy/starting.  I have been unable to get anything out of the linkstack container in terms of logs to indicate what is going wrong. If I attempt a health check, I get a HTTP 500 from the linkstack Apache.  

### Details about your system

Docker

### How to reproduce

Traefik container in front of a linkstack container

**Comment by MattDevTec** [comment]
Hi, 

I have personally it running, bare with me I will share the guide what I used

**Comment by linuxuser332** [comment]
Thanks man.  I'm absolutely cooked with this thing.  It's doing my nut in. 

I am using the following compose file for my linkstack container:
`services:
  app:
    image: linkstackorg/linkstack
    container_name: shg-linkstack
    restart: no
    volumes:
      - ./persist:/htdocs
    expose:
      - "443"
    networks:
      - web-services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shg-linkstack.rule=Host(`mywebsite.com`)"
      - "traefik.http.routers.shg-linkstack.tls=true"
      - "traefik.http.routers.shg-linkstack.tls.certResolver=default"
      - "traefik.http.routers.shg-linkstack.service=shg-linkstack"
      - "traefik.http.routers.shg-linkstack.middlewares=shg-linkstack-head"
      - "traefik.http.services.shg-linkstack.loadBalancer.server.port=443"
      - "traefik.http.services.shg-linkstack.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.shg-linkstack-head.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.shg-linkstack-head.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.shg-linkstack-head.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"
      - "traefik.http.middlewares.shg-linkstack-head.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.shg-linkstack-head.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - HTTPS_SERVER_NAME=mywebsite.com
      - LOG_LEVEL=debug

networks:
  web-services:
    external: true
`

I'm particularly aggrieved that the container is failing its healthcheck and yet there's nothing in the logs, even with LOG_LEVEL set to debug :(

**Comment by MattDevTec** [comment]
I used this: https://goneuland.de/linkstack-mit-docker-und-traefik-installieren/

It is in german but if you translate the web page, it works really well. Worked first time for me

**Comment by MattDevTec** [comment]
@linuxuser332 your docker compose looks a fair bit different, than how I had it configured

**Comment by linuxuser332** [comment]
Okay I have made the labels very closely matched with that page.  eg:

     - "traefik.enable=true"
      - "traefik.http.routers.shg-linkstack.entrypoints=websecure"
      - "traefik.http.routers.shg-linkstack.rule=(Host(`mywebsite.com`))"
      - "traefik.http.routers.shg-linkstack.tls=true"
      - "traefik.http.routers.shg-linkstack.tls.certResolver=default"
      - "traefik.http.routers.linkstack.service=shg-linkstack"
      - "traefik.http.services.shg-linkstack.loadbalancer.server.port=80"
      - "traefik.docker.network=web-services"
      - "traefik.http.routers.shg-linkstack.middlewares=default@file,shg-linkstack-head"
      - "traefik.http.middlewares.shg-linkstack-head.headers.customrequestheaders.X-forwarded-Proto=https"
      - "traefik.http.middlewares.shg-linkstack-head.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.shg-linkstack-head.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"
      - "traefik.http.middlewares.shg-linkstack-head.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.linkstack-head.headers.accesscontrolalloworiginlist=*"

There is no change.  I attempt to get to the site, and traefik gives a 404 page not found error. Hmmm

**Comment by linuxuser332** [comment]
I found it.  The key issue I had came down to filesystem permissions.  A chown -R 100:101 in my persist directory and the application is now working again.  Be careful when editing the .env people, and make sure the permissions are correct!

Thanks

**Comment by MattDevTec** [comment]
Perfect :)
Glad it helped you fix the issue

**Comment by linuxuser332** [comment]
Permissions issue
